services:
  database:
    image: postgres:16.0-alpine3.18
    container_name: strapi-postgres
    env_file:
      - ../../.env.development
    ports:
      - "2345:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
